from models.process import Process
from pwd import getpwuid
import socket


def nslookup_helper(domain):
    ip = ""

    if domain[0].isalpha():
        ip = socket.getaddrinfo(domain, 0)[0][4][0]
    else:
        ip = domain

    return ip


def get_username_by_uid(uid=1000):
    try:
        return getpwuid(uid).pw_name
    except KeyError:
        return None


def create_fake_processes():
    processes = [
        Process(
            pid=1,
            tty="?",
            time="00:00:09",
            command="systemd",
            uid=0,
            ppid=0,
            c=2503,
            stime="12:30",
            stat="S",
            sid=1,
            cpu=0.2,
            mem=0.0,
            rss=11888,
            vsz=170260,
            # ucmd="/sbin/init splash",
        ),
        # Process(
        #     2,
        #     "?",
        #     "00:00:00",
        #     "kthreadd",
        #     "root",
        #     0,
        #     0,
        #     "12:30",
        #     "S",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[kthreadd]",
        # ),
        # Process(
        #     3,
        #     "?",
        #     "00:00:00",
        #     "rcu_gp",
        #     "root",
        #     "0",
        #     "0",
        #     "12:30",
        #     "I<",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[rcu_gp]",
        # ),
        # Process(
        #     4,
        #     "?",
        #     "00:00:00",
        #     "rcu_par_gp",
        #     "root",
        #     "0",
        #     "0",
        #     "12:30",
        #     "I<",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[rcu_par_gp]",
        # ),
        # Process(
        #     5,
        #     "?",
        #     "00:00:00",
        #     "slub_flushwq",
        #     "root",
        #     "0",
        #     "0",
        #     "12:30",
        #     "I<",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[slub_flushwq]",
        # ),
        # Process(
        #     6,
        #     "?",
        #     "00:00:00",
        #     "netns",
        #     "root",
        #     "0",
        #     "0",
        #     "12:30",
        #     "I<",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[netns]",
        # ),
        # Process(
        #     8,
        #     "?",
        #     "00:00:00",
        #     "kworker/0:0H-events_highpri",
        #     "root",
        #     "0",
        #     "0",
        #     "12:30",
        #     "I<",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[kworker/0:0H-events_highpri]",
        # ),
        # Process(
        #     10,
        #     "?",
        #     "00:00:00",
        #     "mm_percpu_wq",
        #     "root",
        #     "0",
        #     "0",
        #     "12:30",
        #     "I<",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "[mm_percpu_wq]",
        # ),
        # Process(
        #     1673,
        #     "tty2",
        #     "00:00:00",
        #     "gdm-x-session",
        #     "user1",
        #     "0",
        #     "2503",
        #     "12:31",
        #     "S",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "/usr/lib/gdm3/gdm-x-session --run-script env GNOME_SHELL_SESSION_MODE=ubuntu",
        # ),
        # Process(
        #     1675,
        #     "tty2",
        #     "00:00:00",
        #     "Xorg",
        #     "user1",
        #     "0",
        #     "0",
        #     "12:32",
        #     "S",
        #     "0",
        #     "0.8",
        #     "0.0",
        #     "0",
        #     "0",
        #     "/usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -back",
        # ),
        # Process(
        #     1682,
        #     "tty2",
        #     "00:00:00",
        #     "gnome-keyring-d",
        #     "user1",
        #     "0",
        #     "0",
        #     "12:32",
        #     "S",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "/usr/libexec/gnome-session-binary --systemd -systemd -session=ubuntu",
        # ),
        # Process(
        #     2587,
        #     "pts/0",
        #     "00:00:00",
        #     "bash",
        #     "user1",
        #     "0",
        #     "0",
        #     "12:32",
        #     "S",
        #     "0",
        #     "0.0",
        #     "0.0",
        #     "0",
        #     "0",
        #     "bash",
        # ),
    ]

    return processes
